### ISSUE TITLE
switching doesnt change the jdk version ?

### ISSUE THREAD

**Issue by Co18** [DxxxxY/jman#1]
i ran as administrator used the arrow key to change the jdk version
first tried to jdk1.8.0_202
didnt work the jdk version was still on 17.0.2
then tried again same thing
i dont know what i did wrong there isnt any error

**Comment by dxxxxy** [comment]
How are you checking the version? Make sure to close and reopen the terminal because changes to PATH are not refreshed there.

**Comment by dxxxxy** [comment]
You should also show the log the app shows before it disapears.

**Comment by Co18** [comment]
i checked the jdk version using "java -version"
didnt notice there is a log bc the cmd popup was hiding it
![Screenshot 2022-10-19 161232](https://user-images.githubusercontent.com/98058318/196700793-b3c64d8d-a8e3-467f-8cd2-10c05cf54601.png)
here is a ss i took of it if it helps in some way

**Comment by Co18** [comment]
and i prob did something mega retarded

**Comment by dxxxxy** [comment]
Can you confirm that you closed and re-opened the terminal to do `java -version` after it said done?

**Comment by Co18** [comment]
yes i did

**Comment by dxxxxy** [comment]
Hmm, this is weird. Can you `echo %PATH%` and `echo %JAVA_HOME%` in the terminal before and after changing jdk? Don't forget to reopen the terminal.

**Comment by Co18** [comment]
doesnt change anything 
idk
btw when i did echo %java_home% it gave the file path C:\Program Files\Java\jdk1.8.0_202
but using java -version still shows im on jdk 17

**Comment by dxxxxy** [comment]
> doesnt change anything 
> 
> idk
> 
> btw when i did echo %java_home% it gave the file path C:\Program Files\Java\jdk1.8.0_202
> 
> but using java -version still shows im on jdk 17

and what did echo %PATH% print?
